# Generated by Django 3.0.3 on 2020-03-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('return_date', models.DateField(verbose_name='return date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Book')),
                ('library_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.LibraryUser')),
            ],
        ),
    ]
