# Generated by Django 3.0.3 on 2020-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200305_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='checkout_date',
            field=models.DateField(help_text='Checkout date', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(help_text='Return date', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(verbose_name='Reserve'),
        ),
    ]
