# Generated by Django 3.0.3 on 2020-03-09 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_auto_20200309_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 13, 32, 53, 197317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 13, 32, 53, 197317, tzinfo=utc)),
        ),
    ]
