# Generated by Django 3.0.3 on 2020-03-09 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20200309_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 13, 35, 45, 491929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 13, 35, 45, 491929, tzinfo=utc)),
        ),
    ]
