# Generated by Django 3.0.3 on 2020-03-09 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_auto_20200309_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 16, 22, 37, 94276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 16, 22, 37, 94276, tzinfo=utc)),
        ),
    ]
