# Generated by Django 3.0.3 on 2020-03-09 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_auto_20200309_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 16, 35, 26, 420138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='library_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.LibraryUser'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 16, 35, 26, 420138, tzinfo=utc)),
        ),
    ]
